server:
  port: 8081

spring:
  application:
    name: base-service
  # 数据源
  datasource:
    username: lostpass
    password: 123456
    url: jdbc:mysql://localhost:3306/server_lostpass?serverTimezone=Asia/Shanghai&Unicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.ligen.server.**.entity.po

logging:
  level:
    cn.ligen.server.base.service: DEBUG
    cn.ligen.server.base.mapper: DEBUG
    cn.ligen.server.*: DEBUG


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    #operations-sorter: order
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'lostpass'
      paths-to-match: '/**'
      packages-to-scan: cn.ligen.server
  default-flat-param-object: true
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
  documents:
    - name: 测试标题
      locations: classpath:markdown/*
      group: lostpass
  basic:
    enable: false
    username: abc
    password: 123


# 自定义数据配置
user:
  headerUrl: https://gitee.com/ligen0121/PicBed/blob/master/header/header
token:
  key: ligen-wendan